Models/PollViewModel.cs
using BLL.Models;
namespace TALPA.Models
{
    public class PollViewModel
	{
        public bool PollActive { get; set; }
		public bool PollChosen { get; set; }
		public Poll Poll { get; set; }
	}
}

Models/SuggestionsViewModel.cs
using BLL.Models;
namespace TALPA.Models
{
    public class SuggestionsViewModel
	{
		public List<Suggestion> Suggestions { get; set; }
		public List<string> Categories { get; set; }
		public List<string> Limitations { get; set; }
		public string Search { get; set; }
		public string Sort { get; set; }
		public List<string> Filter { get; set; }
		public List<string> Selected { get; set; }
		public List<int> SelectedIds { get; set; }
		public List<string> Closed { get; set; }
		public int Results { get; set; }
	}
}

Models/activityViewModel.cs
using BLL.Models;
namespace TALPA.Models
{
    public class ActivityViewModel
	{
        public bool ActivityPlanned { get; set; }
		public Activity Activity { get; set; }
	}
}

Controllers/ActivityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TALPA.Models;
using BLL;

namespace TALPA.Controllers
{
    public class ActivityController : Controller
    {
        private readonly SuggestionManager suggestionManager;
        private readonly EmployeeManager employeeManager;

        public ActivityController()
        {
            suggestionManager = new SuggestionManager();
            employeeManager = new EmployeeManager();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult CreateSuggestion(object model)
        {
            if (ModelState.IsValid)
            {
                
            }
            return Redirect("/dashboard");
        }
    }
}

Controllers/AppController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TALPA.Models;
using BLL.Models;
using System.Linq.Expressions;
using BLL;
using Microsoft.IdentityModel.Tokens;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using TALPA_ai_test;

namespace TALPA.Controllers
{
	public class AppController : Controller
    {
		private readonly EmployeeUtility employeeUtility;
		private readonly ActivityManager activityManager;
		private readonly SuggestionManager suggestionManager;
		private readonly PollManager pollManager;
		private readonly AiManager aiManager;

		public AppController()
		{
			employeeUtility = new EmployeeUtility();
			activityManager = new ActivityManager();
			suggestionManager = new SuggestionManager();
			pollManager = new PollManager();
			aiManager = new AiManager();
		}

		[Authorize]
		public IActionResult Activity()
        {
			Employee employee = employeeUtility.GetEmployee(User);
			ViewBag.Employee = employee;


			bool ActivityPlanned = activityManager.ActivityPlanned(employee.Team);

			ActivityViewModel activityViewModel = new ActivityViewModel
            {
				ActivityPlanned = ActivityPlanned,
			};

            if (ActivityPlanned)
            {
                activityViewModel.Activity = activityManager.GetActivity(employee.Team);

			}

            if (activityViewModel.ActivityPlanned)
            {
	            ActivityManager am = new();

	            if (am.RemoveActivityAfterDeadline(am.GetPlannedActivityIdByTeamName(employee.Team),
		                Convert.ToDateTime(activityViewModel.Activity.StartDate)))
	            {
		            return Redirect("/uitje");
				}
            }
            return View(activityViewModel);
        }

		[Authorize]
		public IActionResult Suggestions()
        {
			Employee employee = employeeUtility.GetEmployee(User);
			ViewBag.Employee = employee;
			ViewBag.message = TempData["message"] ?? "";
            ViewBag.errorMessage = TempData["errorMessage"] ?? "";

            string  search = Request.Query["search"];
            string sort = Request.Query["sort"];
			string filter = Request.Query["filter"];
			string selected = Request.Query["selected"];
			string selectedIds = Request.Query["ids"];
			string closed = Request.Query["closed"];

			search = string.IsNullOrEmpty(search) ? "" : search;
            sort = string.IsNullOrEmpty(sort) ? "trending" : sort;
			filter = string.IsNullOrEmpty(filter) ? "" : filter;
			selected = string.IsNullOrEmpty(selected) ? "" : selected;
			selectedIds = string.IsNullOrEmpty(selectedIds) ? "" : selectedIds;
			closed = string.IsNullOrEmpty(closed) ? "" : closed;

			List<string> filterList = filter.Split(' ', StringSplitOptions.RemoveEmptyEntries).ToList();
			List<string> closedList = closed.Split(' ', StringSplitOptions.RemoveEmptyEntries).ToList();
			List<string> selectedList = selected.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(s => s.Replace("-", " ")).ToList();
			List<int> selectedIdsList = selectedIds.Split(' ', StringSplitOptions.RemoveEmptyEntries).Select(int.Parse).ToList();

			List<Suggestion> suggestionResults = suggestionManager.GetSuggestions(employee.Id, search, sort, filterList, selectedIdsList);
			SuggestionsViewModel suggestionsViewModel = new SuggestionsViewModel
			{
				Suggestions = suggestionResults,
				Categories = suggestionManager.GetCategories(),
				Limitations = suggestionManager.GetLimitations(),
				Search = search,
				Sort = sort,
				Filter = filterList,
				Selected = selectedList,
				SelectedIds =  selectedIdsList,
				Results = suggestionResults.Count,
				Closed = closedList
			};
            return View(suggestionsViewModel);
        }

		[Authorize]
        public IActionResult Poll()
        {
            Employee employee = employeeUtility.GetEmployee(User);
            ViewBag.Employee = employee;
            ViewBag.message = TempData["message"] ?? "";
            ViewBag.errorMessage = TempData["errorMessage"] ?? "";
            bool pollactive = pollManager.PollActive(employee.Team);

            if (pollactive)
            {
                PollViewModel pollViewModel = new PollViewModel
                {
                    PollActive = pollactive,
                    PollChosen = pollManager.PollChosen(employee.Id),
                    Poll = pollManager.GetPoll(employee.Id, employee.Team)
                };

                // Call EndPoll to finalize the poll if the deadline has passed
                if (pollManager.EndPoll(employee.Team))
                {
	                return Redirect("/stemmen");
                }

                return View(pollViewModel);
            }
            else
            {
                PollViewModel pollViewModel = new PollViewModel
                {
                    PollActive = pollactive,
                };
                return View(pollViewModel);
            }
        }

        [Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult SubmitSuggestion(string name, string description, List<string> categories, List<string> limitations)
		{
			if (
				!string.IsNullOrWhiteSpace(name) && 
				!string.IsNullOrWhiteSpace(description) &&
				categories.Any() &&
				limitations.Any() &&
				name.Length >= 5 &&
				name.Length <= 30 &&
				description.Length >= 30 &&
				description.Length <= 150 &&
				categories.Count >= 1 &&
				limitations.Count >= 1
			)
			{
				Employee employee = employeeUtility.GetEmployee(User);
				suggestionManager.SubmitSuggestion(employee.Id, name, description, categories, limitations);
				TempData["message"] = "We hebben je suggestie ontvangen!";
				return Redirect("/suggesties");
			}
			return Content("Invalid");
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult SubmitPoll(string suggestion, List<string> availability)
		{
			if (
				!string.IsNullOrWhiteSpace(suggestion) &&
				availability.Any()
			)
			{
				Employee employee = employeeUtility.GetEmployee(User);
				int suggestionInt = Convert.ToInt32(suggestion);
				pollManager.SubmitPoll(employee.Id, suggestionInt, availability, pollManager.GetPollIdWithTeamName(employee.Team));
				TempData["message"] = "We hebben je Keuze ontvangen!";
				return Redirect("/stemmen");
			}
			return Content("Invalid");
		}

		[Authorize]
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult CreatePoll(List<string> activities, List<string> availability, string deadline, string time)
		{
			if (
				!string.IsNullOrWhiteSpace(deadline) &&
				!string.IsNullOrWhiteSpace(time) &&
				activities.Count >= 3 &&
				availability.Count >= 1
			)
			{
				Employee employee = employeeUtility.GetEmployee(User);
				List<int> activitiesInt = activities.Select(activity => int.Parse(activity)).ToList();
				activitiesInt = activitiesInt.Take(3).ToList();
				string date = deadline + " " + time.Replace(" ", "");
				date = Regex.Replace(date, @"\s+", " ");
				bool created = pollManager.CreatePoll( employee.Team, activitiesInt, date, availability);
				if (created)
				{
					TempData["message"] = "Stemming is aangemaakt!";
                    return Redirect("/stemmen");
                }
				else
				{
					TempData["errorMessage"] = "Er is al een stemming bezig!";
                    return Redirect("/suggesties");
                }
			}
			return Content("Invalid");
		}

        [HttpPost]
        [Authorize]
		public async Task<IActionResult> GetSimilarSuggestions(string name, string description)
		{
			if (
				!string.IsNullOrWhiteSpace(name) &&
				!string.IsNullOrWhiteSpace(description)
			)
			{
				List<string> SqlInjections = new List<string> { "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "UNION", "WHERE", "AND", "OR", "LIKE", "EXEC", "EXECUTE", "TRUNCATE", "ORDER BY", "GROUP BY", "--", ";", "/*", "*/", "XP_CMDShell" };
				if (SqlInjections.Any(keyword => name.Contains(keyword) || description.Contains(keyword)))
				{
					return Content("Nice Try! Ik ga je kietelen.");
				}

				Employee employee = employeeUtility.GetEmployee(User);
				List<Suggestion> suggestions = suggestionManager.GetSuggestions(employee.Id, "", "popular", new List<string>(), new List<int>());
				Suggestion suggestion = new Suggestion
				{
					Name = name,
					Description = description
				};

				List<int> similars = await aiManager.GetSimilars(suggestions, suggestion);
				return Json(similars);
			}
			return Content("Invalid");
		}
	}
}

Views/App/Activity.cshtml
@{
	Layout = "_DashboardLayout";
	ViewData["Title"] = "Uitje";
	ViewData["Page"] = "Uitje";
}

@model TALPA.Models.ActivityViewModel

<h1 class="mb-3">Huidig uitje</h1>

@if (Model.ActivityPlanned)
{
	<div class="card h-100">
		<div class="card-header">
			<div class="d-md-flex align-items-center justify-content-between">
				<div>
					<a class="text-btn" target="_blank" href="https://maps.google.com/?q=@Model.Activity.Location">@Model.Activity.Location</a>
					<br />
					<p class="mb-md-0">@Model.Activity.StartDate</p>
				</div>
				<a class="btn" target="_blank" href="https://calendar.google.com/calendar/u/0/r/eventedit?text=Bedrijfs+uitje:+@System.Web.HttpUtility.UrlEncode(Model.Activity.Name)&dates=@DateTime.ParseExact(Model.Activity.StartDate, "dd-MM-yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture).ToString("yyyyMMddTHHmmss")/@DateTime.ParseExact(Model.Activity.StartDate, "dd-MM-yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture).ToString("yyyyMMddTHHmmss")&location=@System.Web.HttpUtility.UrlEncode(Model.Activity.Location)&details=@System.Web.HttpUtility.UrlEncode(Model.Activity.Description)%0A%0ATeam:+@System.Web.HttpUtility.UrlEncode(ViewBag.Employee.Team)%0ALocatie:+@System.Web.HttpUtility.UrlEncode(Model.Activity.Location)&location=@System.Web.HttpUtility.UrlEncode(Model.Activity.Location)">
					Toevoegen aan agenda
				</a>
			</div>
		</div>
		<div class="card-body">
			<h5 class="card-title overflow-hidden mb-0">@Model.Activity.Name</h5>
			<p class="card-text">@Model.Activity.Description</p>
			<p class="mb-0">Categorie: @string.Join(", ", Model.Activity.Categories)</p>
			<p class="mb-0">Beperkingen: @string.Join(", ", Model.Activity.Limitations)</p>
		</div>
	</div>
} 
else
{
	<div class="text-center">
		<p>Op dit moment zijn er geen uitjes gepland.</p>
		@if (ViewBag.Employee.Role == "Manager")
		{
			<a class="btn" href="/suggesties">Nieuw stemming starten</a>
		}
	</div>
}

Views/App/Poll.cshtml
@{
    Layout = "_DashboardLayout";
    ViewData["Title"] = "Stemmen";
    ViewData["Page"] = "Stemmen";
}

@model TALPA.Models.PollViewModel

<div class="d-md-flex align-items-center justify-content-between mb-3">
	<h1>Stem op je favoriete uitje</h1>
	@if (Model.PollActive)
	{
		<p class="mb-0"><small class="text-muted">Einddatum: @Model.Poll.Deadline</small></p>
	}
</div>

@if (Model.PollActive)
{
	@if (Model.PollChosen)
	{
		<p class="text-center">Mijn beschikbaarheid: @string.Join(", ", @Model.Poll.Availability)</p>
	}
	<div class="row">
		@foreach (var suggestion in Model.Poll.Suggestions)
		{
			<div class="col-lg-4 mb-4">
				<div class="card h-100">
					<div class="card-body">
						<div class="d-flex align-items-start justify-content-between mb-2">
							<h5 class="card-title mb-0">@suggestion.Name</h5>
							<p class="card-text ps-3"><small class="text-muted text-nowrap">@suggestion.Votes stemmen</small></p>
						</div>
						<p class="card-text">@suggestion.Description</p>
						<p class="mb-0">Categorie: @string.Join(", ", @suggestion.Categories)</p>
						<p>Beperkingen: @string.Join(", ", @suggestion.Limitations)</p>
						@if (!Model.PollChosen)
						{
							<a class="btn mt-auto" data-bs-toggle="modal" data-bs-target="#pollModal" data-bs-suggestion-id="@suggestion.Id" data-bs-suggestion-name="@suggestion.Name">Uitje Kiezen</a>
						}
					</div>
					@if (Model.PollChosen)
					{
						@if (Model.Poll.ChosenSuggestion == suggestion.Id)
						{
							<div class="d-flex justify-content-center align-items-center position-absolute w-100 h-100 bg-light bg-opacity-75 rounded">
								<svg xmlns="http://www.w3.org/2000/svg" fill="#5236AB" class="bi bi-check h-50" viewBox="0 0 16 16">
									<path d="M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z" />
								</svg>
							</div>
						}
					}
				</div>
			</div>
		}
	</div>
} 
else
{
	<p class="text-center">Op dit moment is er geen stemming bezig.</p>
}

<div class="modal fade" id="pollModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="pollModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="pollModalLabel">Keuze maken</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body">
				<form asp-controller="App" asp-action="SubmitPoll" method="post" id="form">
					@Html.AntiForgeryToken()
					<div class="mb-3">
						<label class="form-label">Uitje</label>
						<input type="text" class="form-control" id="suggestionInput" disabled>
						<input type="hidden" id="suggestionId" name="suggestion">
						<div id="suggestionFeedback" class="invalid-feedback d-block"></div>
					</div>
					<div class="mb-3">
						<label class="form-label">Beschikbaarheid</label>
						<textarea type="text" rows="1" class="form-control dateInput" id="dateInput" placeholder="Selecteer beschikbare dagen" disabled></textarea>
						<div id="dateFeedback" class="invalid-feedback d-block mb-2"></div>
						<div id="datepicker" class="d-flex justify-content-center text-center"></div>
						<select id="dateInputHidden" name="availability" multiple hidden></select>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<a class="btn btn-sec" data-bs-dismiss="modal">Terug</a>
				<a class="btn" id="submitButton">Keuze bevestigen</a>
			</div>
		</div>
	</div>
</div>

@if (Model.PollActive)
{
	@if (!Model.PollChosen)
	{
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/css/bootstrap-datepicker.min.css" asp-append-version="true" />
		<link rel="stylesheet" href="~/styles/calender.css" asp-append-version="true" />
		<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.10.0/js/bootstrap-datepicker.min.js"></script>
		<script asp-append-version="true">
			var availableDates = @Html.Raw(System.Text.Json.JsonSerializer.Serialize(Model.Poll.PossibleDates));
		</script>
		<script src="~/scripts/pollForm.js"></script>
	}
}